use GitHub actions
typelevel/discipline-scalatest pull request #136
Opened 2020-12-02 18:50 UTC by jopecko

https://github.com/typelevel/discipline-scalatest/issues/132

2020-12-02 18:51 UTC, jopecko commented
for your consideration, @larsrh and @djspiewak

2020-12-02 21:04 UTC, djspiewak requested changes
I can re-push this to upstream so that the actions are picked up and run! Thank you for doing this!

2020-12-02 21:28 UTC, jopecko commented on build.sbt
> +ThisBuild / crossScalaVersions := Seq("2.13.3", scalaVersion.value, "2.11.12", "3.0.0-M1")
Will do. Thanks for the sbt plugin that makes this so easy to do!

2020-12-06 09:15 UTC, larsrh commented
Thanks a lot!

2020-12-06 09:16 UTC, closed without merging